spring.application.name=opentelemetrydemo

tracing.url=http://localhost:4318/v1/traces

management.tracing.sampling.probability=1.0

loggin.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]